/*
 * Copyright (C) 2017 Laboratory of Experimental Biophysics
 * Ecole Polytechnique Federale de Lausanne
 * 
 * Author: Marcel Stefko
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.epfl.leb.sass.ijplugin;

import ch.epfl.leb.alica.Analyzer;
import ch.epfl.leb.alica.Controller;

/**
 *
 * @author stefko
 */
public class InteractionWindow extends javax.swing.JFrame {

    /**
     * Creates new form InteractionWindow
     */
    public InteractionWindow(Analyzer analyzer, Controller controller) {
        initComponents();
        
        javax.swing.JPanel a_panel = analyzer.getStatusPanel();
        if (a_panel != null) {
            p_analyzer.add(a_panel);
            a_panel.setBounds(5,5,230,170);
            a_panel.revalidate();
            a_panel.repaint();
            p_analyzer.validate();
            p_analyzer.repaint();
        }
        javax.swing.JPanel c_panel = controller.getStatusPanel();
        if (c_panel != null) {
            p_controller.add(c_panel);
            c_panel.setBounds(5,5,230,170);
            c_panel.revalidate();
            c_panel.repaint();
            p_controller.validate();
            p_controller.repaint();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_analyzer = new javax.swing.JPanel();
        p_controller = new javax.swing.JPanel();

        javax.swing.GroupLayout p_analyzerLayout = new javax.swing.GroupLayout(p_analyzer);
        p_analyzer.setLayout(p_analyzerLayout);
        p_analyzerLayout.setHorizontalGroup(
            p_analyzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        p_analyzerLayout.setVerticalGroup(
            p_analyzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_controllerLayout = new javax.swing.GroupLayout(p_controller);
        p_controller.setLayout(p_controllerLayout);
        p_controllerLayout.setHorizontalGroup(
            p_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        p_controllerLayout.setVerticalGroup(
            p_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_analyzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_controller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_analyzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_controller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel p_analyzer;
    private javax.swing.JPanel p_controller;
    // End of variables declaration//GEN-END:variables
}
